import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.blueGray50,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              4,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Color(0XFFFFFFFF),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: colorScheme.secondaryContainer,
              width: 1,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.blueGray100,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.blueGray900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.blueGray900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.secondaryContainer,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.whiteA700,
          fontSize: getFontSize(
            40,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Lobster',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: appTheme.blueGray900,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w700,
        ),
        labelMedium: TextStyle(
          color: appTheme.blueGray700,
          fontSize: getFontSize(
            10,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.blueGray900,
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.blueGray900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: appTheme.blueGray900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Satoshi',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF4378FF),
    primaryContainer: Color(0X33081F4D),
    secondary: Color(0X33081F4D),
    secondaryContainer: Color(0XFF667085),
    tertiary: Color(0X33081F4D),
    tertiaryContainer: Color(0XFF667085),

    // Background colors
    background: Color(0X33081F4D),

    // Surface colors
    surface: Color(0X33081F4D),
    surfaceTint: Color(0XE5101828),
    surfaceVariant: Color(0XFF667085),

    // Error colors
    error: Color(0XE5101828),
    errorContainer: Color(0XFF225FFF),
    onError: Color(0XFF6993FF),
    onErrorContainer: Color(0XE5101828),

    // On colors(text colors)
    onBackground: Color(0X0C00FC68),
    onInverseSurface: Color(0XFF6993FF),
    onPrimary: Color(0XE5101828),
    onPrimaryContainer: Color(0X0C00FC68),
    onSecondary: Color(0X0C00FC68),
    onSecondaryContainer: Color(0XE5101828),
    onTertiary: Color(0X0C00FC68),
    onTertiaryContainer: Color(0XE5101828),

    // Other colors
    outline: Color(0XE5101828),
    // outlineVariant: Color(0X33081F4D),
    // scrim: Color(0X33081F4D),
    shadow: Color(0XE5101828),

    // Inverse colors
    inversePrimary: Color(0X33081F4D),
    inverseSurface: Color(0XE5101828),

    // Pending colors
    onSurface: Color(0X0C00FC68),
    onSurfaceVariant: Color(0XE5101828),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blue100 => Color(0XFFB4C9FF);
  Color get blue50 => Color(0XFFDAE4FF);
  Color get blue5001 => Color(0XFFE9EFFF);

  // BlueGray
  Color get blueGray100 => Color(0XFFD0D5DD);
  Color get blueGray10001 => Color(0XFFD9D9D9);
  Color get blueGray300 => Color(0XFF98A2B3);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray50 => Color(0XFFEAECF0);
  Color get blueGray700 => Color(0XFF475467);
  Color get blueGray900 => Color(0XFF1D2939);

  // Gray
  Color get gray100 => Color(0XFFF4F5F6);
  Color get gray10001 => Color(0XFFECFDF3);
  Color get gray300 => Color(0XFFE1E1E1);
  Color get gray50 => Color(0XFFF9F9FA);

  // Indigo
  Color get indigo50 => Color(0XFFE4E8EE);

  // Pink
  Color get pink400 => Color(0XFFF03864);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
